### ISSUE TITLE
Weird crash on Android

### ISSUE THREAD

**Issue by d3mac123** [dapriett/nativescript-google-maps-sdk#154]
As a new designer/hobbyist developer trying to create my first app with Nativescript, I am getting this weird error on Android (everything is working fine on iOS):
An uncaught Exception occurred on "main" thread.
com.tns.NativeScriptException: 
Calling js method onCreateView failed

Error: java.lang.NoClassDefFoundError: com.google.android.gms.maps.model.CameraPosition
    com.google.android.gms.maps.model.CameraPosition$Builder.build(Unknown Source)
    com.tns.Runtime.callJSMethodNative(Native Method)
    com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1197)
    com.tns.Runtime.callJSMethodImpl(Runtime.java:1061)
    com.tns.Runtime.callJSMethod(Runtime.java:1047)
    com.tns.Runtime.callJSMethod(Runtime.java:1028)
    com.tns.Runtime.callJSMethod(Runtime.java:1018)
    com.tns.FragmentClass.onCreateView(android.app.Fragment.java)
    android.app.Fragment.performCreateView(Fragment.java:2220)
    android.app.FragmentManagerImpl.moveToState(FragmentManager.java:973)
    android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1148)
    android.app.BackStackRecord.run(BackStackRecord.java:793)
    android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1535)
    android.app.FragmentManagerImpl$1.run(FragmentManager.java:482)
    android.os.Handler.handleCallback(Handler.java:739)
    android.os.Handler.dispatchMessage(Handler.java:95)
    android.os.Looper.loop(Looper.java:148)
    android.app.ActivityThread.main(ActivityThread.java:5417)
    java.lang.reflect.Method.invoke(Native Method)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
File: "file:///data/data/com.asouza.buddyFinder/files/app/tns_modules/nativescript-google-maps-sdk/map-view.js, line: 46, column: 36

StackTrace: 
	Frame: function:'MapView._createCameraPosition', file:'file:///data/data/com.asouza.buddyFinder/files/app/tns_modules/nativescript-google-maps-sdk/map-view.js', line: 46, column: 37
	Frame: function:'MapView._createUI', file:'file:///data/data/com.asouza.buddyFinder/files/app/tns_modules/nativescript-google-maps-sdk/map-view.js', line: 167, column: 35
	Frame: function:'View._onContextChanged', file:'file:///data/data/com.asouza.buddyFinder/files/app/tns_modules/tns-core-modules/ui/core/view.js', line: 202, column: 14
	Frame: function:'View._onAttached', file:'file:///data/data/com.asouza.buddyFinder/files/app/tns_modules/tns-core-modules/ui/core/view.js', line: 153, column: 14
	Frame: function:'eachChild', file:'file:///data/data/com.asouza.buddyFinder/files/app/tns_modules/tns-core-modules/ui/core/view.js', line: 158, column: 23
	Frame: function:'LayoutBase._eachChildView', file:'file:///data/data/com.asouza.buddyFinder/files/app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js', line: 144, column: 22
	Frame: function:'View._onAttached', file:'file:///data/data/com.asouza.buddyFinder/files/app/tns_modules/tns-core-modules/ui/core/view.js', line: 165, column: 18
	Frame: function:'eachChild', file:'file:///data/data/com.asouza.buddyFinder/files/app/tns_modules/tns-core-modules/ui/core/view.js', line: 158, column: 23
	Frame: function:'ContentView._eachChildView', file:'file:///data/data/com.asouza.buddyFinder/files/app/tns_modules/tns-core-modules/ui/content-view/content-view.js', line: 65, column: 13
	Frame: function:'Page._eachChildView', file:'file:///data/data/com.asouza.buddyFinder/files/app/tns_modules/tns-core-modules/ui/page/page-common.js', line: 317, column: 41
	Frame: function:'View._onAttached', file:'file:///data/data/com.asouza.buddyFinder/files/app/tns_modules/tns-core-modules/ui/core/view.js', line: 165, column: 18
	Frame: function:'View._addViewCore', file:'file:///data/data/com.asouza.buddyFinder/files/app/tns_modules/tns-core-modules/ui/core/view.js', line: 126, column: 18
	Frame: function:'View._addView', file:'file:///data/data/com.asouza.buddyFinder/files/app/tns_modules/tns-core-modules/ui/core/view-common.js', line: 1163, column: 14
	Frame: function:'onFragmentShown', file:'file:///data/data/com.asouza.buddyFinder/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 40, column: 11
	Frame: function:'FragmentCallbacksImplementation.onCreateView', file:'file:///data/data/com.asouza.buddyFinder/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 612, column: 13
	Frame: function:'FragmentClass.onCreateView', file:'file:///data/data/com.asouza.buddyFinder/files/app/tns_modules/tns-core-modules/ui/frame/fragment.js', line: 23, column: 38

	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1197)
	at com.tns.Runtime.callJSMethodImpl(Runtime.java:1061)
	at com.tns.Runtime.callJSMethod(Runtime.java:1047)
	at com.tns.Runtime.callJSMethod(Runtime.java:1028)
	at com.tns.Runtime.callJSMethod(Runtime.java:1018)
	at com.tns.FragmentClass.onCreateView(android.app.Fragment.java)
	at android.app.Fragment.performCreateView(Fragment.java:2220)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:973)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1148)
	at android.app.BackStackRecord.run(BackStackRecord.java:793)
	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1535)
	at android.app.FragmentManagerImpl$1.run(FragmentManager.java:482)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5417)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.NoClassDefFoundError: com.google.android.gms.maps.model.CameraPosition
	at com.google.android.gms.maps.model.CameraPosition$Builder.build(Unknown Source)
	... 20 more

Any idea on what to do to fix it?

**Comment by ADjenkov** [comment]
Same exception. Using {N} 3.0 Angular 2

**Comment by dapriett** [comment]
Not able to replicate - both demo and ng-demo samples work with 3.0.

`Error: java.lang.NoClassDefFoundError: com.google.android.gms.maps.model.CameraPosition`

That would tell me that it can't find the Android Google Maps SDK - make sure you have it installed.  Also make sure you're using the latest version of the plugin. 

If there are still issues, reopen the issue.
