### ISSUE TITLE
Update the plugin in order to use the latest libraries (PR) 

### ISSUE THREAD

**Issue by funder7** [dapriett/nativescript-google-maps-sdk#422]
Hello,

I've created a PR which is built around the new nativescript libraries (@nativescript/x). 

Actually this has been tested on Android (emulator), a test on iOS would be nice in case the changes will be approved.

#420 

@dapriett can you check it? thanks :)

**Comment by alexisconsuegra** [comment]
Hi @funder7 . Is this plugin been maintained at all? I see lots of open issues with out a response. I noticed the marker is no longer showing also. I just posted one issue a few days ago. I am trying to build ios with xCode 10.1.0 but it fails.
Have you been able to do local builds?
Thanks,
Alexis

Undefined symbols for architecture i386:
"___isPlatformVersionAtLeast", referenced from:
-[GMSCellularInfo SIMCountryCode] in GoogleMaps
-[GMSScreenInfo initWithUIScreen:] in GoogleMaps
-[GMSx_QTMCollectionViewController viewDidLoad] in GoogleMaps
-[GMSx_QTMCollectionViewController viewDidLayoutSubviews] in GoogleMaps
-[GMSx_QTMCollectionViewStyleController contentViewInsetsForCellWithAttribute:] in GoogleMaps
-[GMSx_QTMCollectionViewStyleController setInsetsContentViewsToSafeArea:] in GoogleMaps
-[GMSx_QTMCollectionViewStyleController insetsAtSectionIndex:] in GoogleMaps
...
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
note: Using new build systemnote: Planning buildnote: Constructing build description
** BUILD FAILED **

Command xcodebuild failed with exit code 65

**Comment by funder7** [comment]
Hi, @alexisconsuegra, I don't know what are the author's intentions about this, I'm waiting for a reply too.. About your problem, let's continue the discussion in your issue!

**Comment by flocca** [comment]
Same problem here, markers not showing. Any workaround?

**Comment by funder7** [comment]
I have the fix, I'll push it tomorrow

**Comment by flocca** [comment]
Thank you @funder7, I can't wait to try your fix.

**Comment by funder7** [comment]
Hi @flocca sorry but I had some delay, I'll push the changes this weekend hopefully.

**Comment by ubaidazad** [comment]
after upgrading to 7.x map is not showing map at all, it was working in 6.x
![address image](https://user-images.githubusercontent.com/11173794/94143816-facffd00-fe8d-11ea-94ec-46bafd05b335.jpeg)

**Comment by funder7** [comment]
Hello @ubaidazad thanks for reporting it. I will definitively check it this weekend to see if I can make it be compatible with the latest {N} version.

**Comment by ubaidazad** [comment]
any progress here?

**Comment by postescu** [comment]
apparently not...

**Comment by funder7** [comment]
Sorry guys I'm doing this in my free time, which is inexistent in the last weeks... Probably I'll meet with other people during the next weekend to complete the update.

**Comment by postescu** [comment]
thank you. we apreciate. there is a PR that looks like it fixes a lot of compat issues... when you have time...  
thanks a lot

**Comment by funder7** [comment]
> after upgrading to 7.x MapView is not showing map at all, it was working in 6.x
> ![address image](https://user-images.githubusercontent.com/11173794/94143816-facffd00-fe8d-11ea-94ec-46bafd05b335.jpeg)
> 

On which platform? 
Can you try to run on the other one as well and check if is not showing as well? Thanks

**Comment by funder7** [comment]
> thank you. we apreciate. there is a PR that looks like it fixes a lot of compat issues... when you have time...  
> thanks a lot

No worries, I wish I had the time to close it now as it doesn't look like there's much to end the update.
Which PR are you referring to?

**Comment by ubaidazad** [comment]
> On which platform?
> Can you try to run on the other one as well and check if is not showing as well? Thanks

@funder7 
platform: **Android Device**
What other one are you referring to?

**Comment by stefalda** [comment]
Just a note:
 in Android with ns 6.8.0 and tns-android 6.5.3 the Map is not displayed at all, while in iOS it seems ok...
